name: Call website deployment pipeline

on:
  workflow_dispatch: # to test
  push:
    branches:
      - main #on push to the master branch do the jobs below

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SSW_WEBSITE_ACCESS_TOKEN }}
          repository: SSWConsulting/SSW.Website
          event-type: content-deploy